crud/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  
  get	'/posts', to:	'posts#index'  
  get	'/posts', to:	'posts#new'
  post	'/posts', to:	'posts#create'
  get	'/posts/:id/edit', to: 'posts#edit'
  get	'/posts/:id', to: 	'posts#show'
  put	'/posts/:id', to: 'posts#update'
 delete	'/posts/:id', to: 	'posts#destroy'
 

end

crud/app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title
end

crud/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

crud/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params.require(:post).permit(:title,:body))
    if @post.save
      redirect_to posts_path
    else
      render :action => 'new'
    end
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    if @post.update_attributes params.require(:post).permit(:title,:body)
      redirect_to posts_path
    else
      render :action => :edit
    end
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to posts_path
  end

  def show
    @post = Post.find params[:id]
  end

end

crud/app/helpers/application_helper.rb
module ApplicationHelper
end

crud/app/helpers/posts_controller_helper.rb
module PostsControllerHelper
end

crud/app/helpers/posts_helper.rb
module PostsHelper
end

crud/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

crud/app/views/posts/edit.html.erb
<%= form_for @post,:url =>{:action => "update", :id =>@post} do |form| %>
<%= "Title" %></br>
  <%= form.text_field :title %></br>
  <%= "Body" %></br>
  <%= form.text_area :body %></br>
  <%= form.submit %>
<% end -%>

crud/app/views/posts/index.html.erb
<h1>List of posts</h1>

<table border="1">
  <thead>
    <tr>
      <th>Title</th>
      <th>Options</th>
    </tr>
  </thead>
<%  @posts.each do |post| %>
  <tr>
     <td><%= link_to post.title,{:action => "show", :id => post.id} %></td>
     <td><%= link_to 'Edit', {:action => "edit",:id => post.id} %>
	     <%= link_to 'Delete', post_path(post),
	                                   method: :delete,               
									   data: { confirm: 'Are you sure?' } %></td> 
  </tr>
<% end %>
</table>
<br/>
<p><%= link_to 'New Post', :action => 'new' %></p>

crud/app/views/posts/new.html.erb
<%= form_for @post,:url =>{:action => "create", :id =>@post} do |form| %>

<%= "Title" %></br>
  <%= form.text_field :title , :required => true  %></br>
  <%= "Body" %></br>
  <%= form.text_area :body %></br>
  <%= form.submit %>
  <%= link_to 'Back', {:action => 'index'} %>
<% end -%>

crud/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= @post.body %></br></br>


<%= link_to 'Edit', :action => 'edit' %></br></br>

<%= link_to 'Back to Home', :action => 'index' %></br>

<p><%= link_to 'New Post', :action => 'new' %></p>